# Generated by Django 5.1.3 on 2024-11-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_fill_name',
            new_name='shipping_full_name',
        ),
    ]
