# Generated by Django 5.1.3 on 2024-11-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_shippingaddress_shipping_address2_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_ordered',
            new_name='date_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
